name: Browserstack (Manual Dispatch)

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to test, in form of \"browser_[browserVersion | :device]_os_osVersion\"'
        required: false
        type: string
        default: 'chrome__windows_11'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build jQuery Mousewheel
        run: npm run build

      - name: Run tests
        run: npm run test:unit -- \
          -v --browserstack ${{ inputs.browser }} \
          -f module=${{ inputs.module }}
