name: Browserstack

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 22.x
    name: ${{ matrix.BROWSER }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.BROWSER }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        BROWSER:
          - 'IE_11'
          - 'Safari_latest'
          # JTR doesn't take into account the jump from Safari 18 to 26,
          # so we need to specify versions explicitly.
          # See https://github.com/jquery/jquery-test-runner/issues/17
          - 'Safari_18'
          - 'Chrome_latest'
          - 'Chrome_latest-1'
          - 'Opera_latest'
          - 'Edge_latest'
          - 'Edge_latest-1'
          - 'Firefox_latest'
          - 'Firefox_latest-1'
          - '_:iPhone 17_iOS_26'
          - '_:iPhone 16_iOS_18'
          - '_:iPhone 15 Pro_iOS_17'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-npm-lock-

      - name: Install dependencies
        run: npm install

      - name: Build jQuery Mousewheel
        run: npm run build

      - name: Run tests
        run: |
          npm run test:unit -- -v --retries 3 --hard-retries 1 \
            --browserstack "${{ matrix.BROWSER }}" \
            --run-id ${{ github.run_id }}
