name: Browserstack (Manual Dispatch)

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to test, in form of \"browser_[browserVersion | :device]_os_osVersion\"'
        required: false
        type: string
        default: 'chrome__windows_11'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 22.x
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build jQuery Mousewheel
        run: npm run build

      - name: Run tests
        run: npm run test:unit -- \
          -v --browserstack ${{ inputs.browser }} \
          -f module=${{ inputs.module }}
